settings:
  displayErrorDetails: false
  email:
    sender: formgenerator@example.com
    host: 127.0.0.1
    port: 25
    encryption: ~
    username: ~
    password: ~
  fileExporter:
    dir: export
  errorMessageNotFound: 'Form not found!'
  errorMessageGeneral: 'Unknown error!!'
